import { ReactNode } from 'react';
import Link from 'next/link';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next app-router',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header style={{ display: 'flex', flexDirection: 'column' }}>
          <Link href={'/'}>home</Link>
          <Link href={'/users'}>users</Link>
          <Link href={'/posts'}>posts</Link>
          <Link href={'/slots'}>slots</Link>
          <Link href={'/clients'}>clients</Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
